import React from 'react';
import Head from 'next/head';
import Header from '../components/header/Header';
import Contacts from '../components/contacts/Contacts';
import MessageUs from '../components/messageUs/MessageUs';
import Footer from '../components/footer/Footer';
import styles from '../components/contact_us/ContactUs.module.css';

function Contact_us() {
	return (
		<div>
			<Head>
				<title>Contact us</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className = {styles.main}>
				<h1>Contact us</h1>
				<section className = {styles.contact}>
					<Contacts />
					<MessageUs />
				</section>
				<section className = {styles.map}>
					Google maps to our site
				</section>
			</main>
			<Footer />
		</div>
	)
}

export default Contact_us