import React from 'react';
import Head from 'next/head';
import Header from '../components/header/Header';
import Project from '../components/project/Project';
import styles from '../components/project/projects.module.css';

function Projects() {
	return (
		<div>
			<Head>
				<title>Projects done</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={styles.main}>
				<h1>Done projects</h1>
				<Project />
			</main>
		</div>
	)
}

export default Projects